### ISSUE TITLE
Change target url endpoint

### ISSUE THREAD

**Issue by msj121** [lucgagan/completions#1]
Might be a good idea to let the endpoint be set so that this library could be used when someone makes their own openai api. Many people self-hosting llm are doing this and matching openai integrations to make it seamless.

https://github.com/lucgagan/completions/blob/125e20b74cb69f62a713f9a04f14d0edceec46b3/src/createCompletions.ts#L117

**Comment by lucgagan** [comment]
Wouldn't their own API endpoint have different parameters though?

**Comment by msj121** [comment]
No, people are modeling their endpoints to duplicate the openai endpoints. This way people can drop in replace their own llm frameworks instead of openai, an interesting idea imo.

**Comment by lucgagan** [comment]
Done!
