### ISSUE TITLE
How to cancel a stream from an external function?

### ISSUE THREAD

**Issue by Kypaku** [lucgagan/completions#6]

**Comment by lucgagan** [comment]
Can you elaborate?

https://github.com/lucgagan/completions#cancelling-responses

Cancelling is generally very simple:

```ts
import { createChat, CancelledCompletionError } from "completions";

const chat = createChat({
  apiKey: OPENAI_API_KEY,
  model: "gpt-3.5-turbo",
});

try {
  await chat.sendMessage("continue sequence: a b c", ({ cancel }) => {
    cancel();
  });
} catch (error) {
  if (error instanceof CancelledCompletion) {
    console.log("cancelled");
  }

  throw error;
}
```

**Comment by Kypaku** [comment]
Yes, I have seen that.
For example, I just want to stop streaming with a click on a button or any other external condition.
For now, it is possible only within the callback.
I think the best solution will look like chat.stopStream()
